package com.Finn.everything_app.model;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

@Entity
@Table(name = "flashcards")
@Data
public class Flashcard {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 1000)
    private String question;

    @Column(nullable = false, length = 2000)
    private String answer;

    @ManyToOne
    @JoinColumn(name = "study_note_id")
    private StudyNote studyNote;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;


    private Integer easeFactor;
    private Integer interval;
    private LocalDateTime nextReviewDate;
    private Integer reviewCount;

    private Boolean autoGenerated;

    private LocalDateTime createdAt;
}