package com.Finn.everything_app.repository;

import com.Finn.everything_app.model.Flashcard;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import java.time.LocalDateTime;
import java.util.List;

@Repository
public interface FlashcardRepository extends JpaRepository<Flashcard, Long> {

    // Alle Karteikarten
    List<Flashcard> findByUserId(Long userId);

    // Karteikarten einer Notiz
    List<Flashcard> findByStudyNoteId(Long studyNoteId);

    // Karteikarten ällig
    @Query("SELECT f FROM Flashcard f " +
            "WHERE f.user.id = :userId " +
            "AND f.nextReviewDate <= :today " +
            "ORDER BY f.nextReviewDate ASC")
    List<Flashcard> findDueCards(
            @Param("userId") Long userId,
            @Param("today") LocalDateTime today
    );

    // Automatisch generierte Karteikarten
    List<Flashcard> findByUserIdAndAutoGeneratedTrue(Long userId);

    // Manuell erstellte Karteikarten
    List<Flashcard> findByUserIdAndAutoGeneratedFalse(Long userId);

    // Karteikarten nach Schwierigkeit
    @Query("SELECT f FROM Flashcard f " +
            "WHERE f.user.id = :userId " +
            "ORDER BY f.easeFactor ASC")
    List<Flashcard> findByDifficulty(@Param("userId") Long userId);

    // Anzahl fälliger Karten
    @Query("SELECT COUNT(f) FROM Flashcard f " +
            "WHERE f.user.id = :userId " +
            "AND f.nextReviewDate <= :today")
    Long countDueCards(
            @Param("userId") Long userId,
            @Param("today") LocalDateTime today
    );
}