import 'dart:async';
import 'package:flutter/material.dart';
import '../models/calendar_event.dart';
import '../services/calendar_service.dart';

class CalendarProvider with ChangeNotifier {
  final CalendarService _calendarService;

  List<CalendarEvent> _events = [];
  bool _isLoading = false;
  String? _error;
  DateTime _focusedDay = DateTime.now();
  DateTime? _selectedDay;
  Timer? _pollingTimer;
  Timer? _reconcileTimer;
  bool _hasAutoGenerated = false;

  /// Wartezeit bis zum Nachladen nach einer Mutation. In Tests auf Duration.zero setzbar,
  /// damit kein laufender Timer die Pending-Timer-Prüfung von flutter_test reißt.
  final Duration reconcileDelay;

  // calendarService is injectable so tests can supply a fake instead of hitting the network.
  CalendarProvider({
    CalendarService? calendarService,
    this.reconcileDelay = const Duration(milliseconds: 600),
  }) : _calendarService = calendarService ?? CalendarService() {
    _startPolling();
  }

  /// Der Backend-Scheduler plant nach jeder Mutation den kompletten Zeitraum neu
  /// (0,4s Entprellung + Solve). Ohne diesen Nachlauf sieht der Nutzer die Umplanung
  /// erst beim 30s-Poll — nach einem Drag-and-Drop fühlt sich das kaputt an.
  ///
  /// Mehrere kurze Versuche statt eines langen Wartens: wann das Ergebnis vorliegt, hängt am
  /// Solver (Zeitbudget 2s) und an der Entprellung, lässt sich hier also nicht vorhersagen.
  /// Ein einzelner Poll zum falschen Zeitpunkt zeigt den alten Stand und der Kalender springt
  /// erst Sekunden später um. Die Leiter deckt den ganzen erwartbaren Bereich ab; ein Poll ist
  /// ein einzelnes GET über den sichtbaren Monat und damit billig.
  static const List<Duration> _reconcileRetries = [
    Duration(milliseconds: 900),
    Duration(milliseconds: 1000),
    Duration(milliseconds: 1200),
  ];

  void scheduleReconcile() {
    _reconcileTimer?.cancel();
    _reconcileTimer = Timer(reconcileDelay, () async {
      await _pollEventsSilent();
      _scheduleReconcileRetry(0);
    });
  }

  void _scheduleReconcileRetry(int index) {
    if (index >= _reconcileRetries.length) return;
    _reconcileTimer = Timer(_reconcileRetries[index], () async {
      await _pollEventsSilent();
      _scheduleReconcileRetry(index + 1);
    });
  }

  void _startPolling() {
    _pollingTimer?.cancel();
    // Poll every 30 seconds to catch background SmartScheduler updates
    _pollingTimer = Timer.periodic(const Duration(seconds: 30), (_) {
      _pollEventsSilent();
    });
  }

  Future<void> _pollEventsSilent() async {
    // Only poll if we have a focused day
    try {
      final month = _focusedDay;
      final firstDay = DateTime(month.year, month.month, 1);
      final lastDay = DateTime(month.year, month.month + 1, 0, 23, 59, 59);
      final newEvents = await _calendarService.getEventsInRange(firstDay, lastDay);
      // We could check if events changed before notifying, but for now just update
      _events = newEvents;
      notifyListeners();
    } catch (e) {
      // ignore silently
    }
  }

  @override
  void dispose() {
    _pollingTimer?.cancel();
    _reconcileTimer?.cancel();
    super.dispose();
  }

  // Getters

  /// Alle sichtbaren Termine — uebersprungene sind bewusst nicht dabei.
  ///
  /// Ueberspringen gibt die Zeit frei; genau so soll der Tag dann auch aussehen. Bliebe der
  /// Block stehen, wuerde der Scheduler die freigegebene Zeit neu belegen und im Kalender laegen
  /// zwei Bloecke uebereinander — das sieht aus wie ein Fehler, obwohl beides stimmt.
  ///
  /// Der Block selbst bleibt serverseitig erhalten (er ist der Beleg fuer das verbrauchte
  /// Wochenpensum); zurueckholen laesst er sich direkt nach dem Ueberspringen ueber das
  /// Rueckgaengig im Hinweis.
  List<CalendarEvent> get events =>
      _events.where((e) => !e.isSkipped).toList(growable: false);
  bool get isLoading => _isLoading;
  String? get error => _error;
  DateTime get focusedDay => _focusedDay;
  DateTime? get selectedDay => _selectedDay;

  List<CalendarEvent> getEventsForDay(DateTime day) {
    // Ueber den Getter, damit uebersprungene Bloecke auch hier nicht auftauchen.
    return events.where((event) {
      return event.startTime.year == day.year &&
             event.startTime.month == day.month &&
             event.startTime.day == day.day;
    }).toList();
  }

  
  List<CalendarEvent> get selectedDayEvents {
    if (_selectedDay == null) return [];
    return getEventsForDay(_selectedDay!);
  }

  
  void setFocusedDay(DateTime day) {
    _focusedDay = day;
    notifyListeners();
  }

  
  void setSelectedDay(DateTime? day) {
    _selectedDay = day;
    notifyListeners();
  }

  
  Future<void> loadEventsForMonth(DateTime month) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final firstDay = DateTime(month.year, month.month, 1);
      final lastDay = DateTime(month.year, month.month + 1, 0, 23, 59, 59);
      
      _events = await _calendarService.getEventsInRange(firstDay, lastDay);
      _error = null;
    } catch (e) {
      _error = 'Fehler beim Laden der Events: $e';
    }

    _isLoading = false;
    notifyListeners();
  }

  
  Future<void> loadEventsInRange(DateTime start, DateTime end) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      _events = await _calendarService.getEventsInRange(start, end);
      _error = null;
    } catch (e) {
      _error = 'Fehler beim Laden der Events: $e';
    }

    _isLoading = false;
    notifyListeners();
  }

  
  Future<bool> addEvent(CalendarEvent event) async {
    debugPrint('🕒 [CalendarProvider] addEvent started');
    try {
      debugPrint('🌐 [CalendarProvider] Calling service.createEvent');
      final created = await _calendarService.createEvent(event);
      
      if (created != null) {
        debugPrint('✅ [CalendarProvider] Event created successfully, reloading month');
        await loadEventsForMonth(_focusedDay);
        debugPrint('📊 [CalendarProvider] Month reloaded');
        scheduleReconcile();
        return true;
      }
      debugPrint('⚠️ [CalendarProvider] service.createEvent returned null');
      return false;
    } catch (e) {
      debugPrint('🔥 [CalendarProvider] Error in addEvent: $e');
      _error = 'Fehler beim Erstellen des Events: $e';
      notifyListeners();
      return false;
    }
  }

  
  // Optimistically applies the change locally (so drag-and-drop feels instant, no
  // full-month reload flicker), then syncs with the backend and reverts on failure.
  Future<bool> updateEvent(CalendarEvent event) async {
    final idx = _events.indexWhere((e) => e.id == event.id);
    final previous = idx != -1 ? _events[idx] : null;

    if (idx != -1) {
      _events[idx] = event;
      notifyListeners();
    }

    try {
      final updated = await _calendarService.updateEvent(event);

      if (updated != null) {
        if (idx != -1) {
          _events[idx] = updated;
          notifyListeners();
        } else {
          await loadEventsForMonth(_focusedDay);
        }
        // Das Backend plant im Hintergrund um — Ergebnis kurz danach nachladen.
        scheduleReconcile();
        return true;
      }
      if (idx != -1 && previous != null) {
        _events[idx] = previous;
        notifyListeners();
      }
      return false;
    } catch (e) {
      if (idx != -1 && previous != null) {
        _events[idx] = previous;
      }
      _error = 'Fehler beim Aktualisieren des Events: $e';
      notifyListeners();
      return false;
    }
  }

  
  Future<bool> deleteEvent(int id) async {
    try {
      final success = await _calendarService.deleteEvent(id);
      
      if (success) {
        await loadEventsForMonth(_focusedDay);
        scheduleReconcile();
        return true;
      }
      return false;
    } catch (e) {
      _error = 'Fehler beim Löschen des Events: $e';
      notifyListeners();
      return false;
    }
  }

  /// Hakt einen Aufgabenblock ab oder nimmt das zurück.
  ///
  /// Anders als [setPinned] bewusst NICHT optimistisch: der Server schreibt die Minuten gut
  /// (ans Lernziel oder an die Aufgabe), schließt die Aufgabe womöglich ab und plant die
  /// restlichen Blöcke neu. Nichts davon lässt sich hier vorhersagen — also gilt, was
  /// zurückkommt.
  Future<bool> setCompleted(int id, bool completed) async {
    try {
      final updated = await _calendarService.setCompleted(id, completed);
      if (updated == null) return false;

      final idx = _events.indexWhere((e) => e.id == id);
      if (idx != -1) {
        _events[idx] = updated;
        notifyListeners();
      }
      // Die Neuplanung läuft entprellt; das Nachladen holt die verschobenen Blöcke.
      scheduleReconcile();
      return true;
    } catch (e) {
      _error = 'Fehler beim Abhaken des Blocks: $e';
      notifyListeners();
      return false;
    }
  }

  /// Überspringt eine Ausführung oder holt sie zurück.
  ///
  /// Wie [setCompleted] und anders als [setPinned] bewusst NICHT optimistisch: das Überspringen
  /// gibt Zeit frei, stößt eine Neuplanung an und markiert bei einem Training zusätzlich die
  /// Session. Was daraus wird, lässt sich hier nicht vorhersagen — also gilt, was zurückkommt.
  Future<bool> setSkipped(int id, bool skipped) async {
    try {
      final updated = await _calendarService.setSkipped(id, skipped);
      if (updated == null) return false;

      final idx = _events.indexWhere((e) => e.id == id);
      if (idx != -1) {
        _events[idx] = updated;
        notifyListeners();
      }
      // Die freigegebene Zeit füllt der Scheduler entprellt nach.
      scheduleReconcile();
      return true;
    } catch (e) {
      _error = 'Fehler beim Überspringen des Blocks: $e';
      notifyListeners();
      return false;
    }
  }

  /// Pinnt ein Event fest oder gibt es wieder für den Scheduler frei.
  /// Optimistisch wie updateEvent, damit das Schloss-Symbol sofort umspringt.
  Future<bool> setPinned(int id, bool pinned) async {
    final idx = _events.indexWhere((e) => e.id == id);
    final previous = idx != -1 ? _events[idx] : null;

    if (idx != -1 && previous != null) {
      _events[idx] = previous.copyWith(isFixed: pinned);
      notifyListeners();
    }

    try {
      final updated = await _calendarService.setPinned(id, pinned);
      if (updated != null) {
        if (idx != -1) {
          _events[idx] = updated;
          notifyListeners();
        }
        scheduleReconcile();
        return true;
      }
      if (idx != -1 && previous != null) {
        _events[idx] = previous;
        notifyListeners();
      }
      return false;
    } catch (e) {
      if (idx != -1 && previous != null) {
        _events[idx] = previous;
      }
      _error = 'Fehler beim Anpinnen des Events: $e';
      notifyListeners();
      return false;
    }
  }

  // Backend auto-regenerates on every task/habit/workout/event change (see ScheduleChangedEvent),
  // but items created before that wiring existed (or edited directly in the DB) need one initial
  // backfill pass. Called once per app session — no user-facing button, this is the "automatic"
  // Reclaim-style scheduling entry point.
  Future<void> ensureScheduleGenerated() async {
    if (_hasAutoGenerated) return;
    _hasAutoGenerated = true;
    await generateSchedule(DateTime.now());
  }


  // Ohne endDate plant das Backend über seinen vollen Horizont — nur so landen Habits und
  // Workouts in jeder Woche und nicht nur in den nächsten zwei.
  Future<Map<String, dynamic>> generateSchedule(
    DateTime startDate, {
    DateTime? endDate,
  }) async {
    _isLoading = true;
    notifyListeners();

    final result = await _calendarService.generateSchedule(startDate, endDate: endDate);

    if (result['success']) {
      // Bewusst den ganzen Monat neu laden, nicht nur [startDate, endDate]: loadEventsInRange
      // ERSETZT _events durch das 14-Tage-Fenster und löscht damit den Monat, der Millisekunden
      // vorher geladen wurde — frühere Tage im Monat sahen danach leer aus.
      await loadEventsForMonth(_focusedDay);
    }

    _isLoading = false;
    notifyListeners();

    return result;
  }

  
  void clearError() {
    _error = null;
    notifyListeners();
  }
}