import 'dart:async';
import 'package:flutter/material.dart';
import '../models/at_risk_item.dart';
import '../models/calendar_event.dart';
import '../services/calendar_service.dart';

class CalendarProvider with ChangeNotifier {
  final CalendarService _calendarService;

  List<CalendarEvent> _events = [];
  bool _isLoading = false;
  String? _error;
  DateTime _focusedDay = DateTime.now();
  DateTime? _selectedDay;
  Timer? _pollingTimer;
  bool _hasAutoGenerated = false;

  // calendarService is injectable so tests can supply a fake instead of hitting the network.
  CalendarProvider({CalendarService? calendarService})
      : _calendarService = calendarService ?? CalendarService() {
    _startPolling();
  }

  /// Zeitpunkt des letzten vom Server gemeldeten Laufs.
  DateTime? _lastRunAt;

  /// Derselbe Zeitpunkt als Rohstring — das ist der Wert, der als `since` zurückgeht.
  String? _lastRunAtRaw;

  bool _replanning = false;

  /// Läuft gerade eine Warte-Anfrage? Verhindert, dass fünf schnelle Ziehbewegungen fünf
  /// geparkte HTTP-Anfragen erzeugen — dieselbe Überlegung wie `laufend` im
  /// ScheduleRegenerationCoordinator auf der Serverseite.
  bool _wartet = false;

  /// Kam während einer laufenden Anfrage eine weitere Änderung? Dann direkt danach nochmal.
  bool _erneutAnfordern = false;

  /// Eine Warte-Anfrage kann bis zu 35 s offen sein und überlebt damit jeden Screenwechsel.
  /// Ohne diese Sperre fliegt "A ChangeNotifier was used after being disposed".
  bool _entsorgt = false;

  /// Misst, wie lange es vom Auslöser bis zum sichtbaren neuen Plan dauert.
  ///
  /// Bleibt dauerhaft drin, aus demselben Grund wie die `SCHED`-Zeile im Backend: ohne eine
  /// Messung ist jede Aussage über "schneller" Glaubenssache. Die Zeile heißt `RECONCILE` und
  /// nennt den Weg, über den die Antwort kam.
  Stopwatch? _reconcileUhr;

  /// Läuft gerade eine Neuplanung, auf deren Ergebnis wir warten?
  bool get isReplanning => _replanning;

  /// Aufgaben, die der Scheduler beim letzten Lauf nicht mehr unterbringen konnte.
  List<AtRiskItem> get atRisk => List.unmodifiable(_atRisk);
  List<AtRiskItem> _atRisk = const [];

  /// Davon nur die, bei denen wirklich eine Deadline auf dem Spiel steht.
  ///
  /// Die Quelle fuers Warnband. Alles andere in [atRisk] heisst nur "noch nicht eingeplant" und
  /// gehoert an die Aufgabe selbst, nicht in ein Warnband ueber dem Kalender.
  List<AtRiskItem> get atRiskDeadlines =>
      _atRisk.where((e) => e.isDeadlineRisk).toList(growable: false);

  /// Bereits gerissene Termine — die schaerfere Haelfte von [atRiskDeadlines], eigenes rotes Band.
  List<AtRiskItem> get atRiskOverdue =>
      _atRisk.where((e) => e.isOverdue).toList(growable: false);

  /// Termine, die noch ausstehen, vor denen aber kein Platz mehr ist.
  List<AtRiskItem> get atRiskUpcoming =>
      _atRisk.where((e) => e.isDeadlineRisk && !e.isOverdue).toList(growable: false);

  /// Nach einer eigenen Änderung auf das Ergebnis der Neuplanung warten.
  ///
  /// Der Backend-Scheduler plant nach jeder Mutation entprellt neu. Früher fragte diese Methode
  /// in einer Retry-Leiter nach (500 ms blind warten, dann 400/600/900/1400/2000 ms). Der Server
  /// war typisch nach 1,4 s fertig, die App zeigte es bei 1,9–2,4 s — die Differenz war reine
  /// Rundung auf das Raster der Leiter, und genau diese Körnung fühlte sich kaputt an.
  ///
  /// Jetzt bleibt eine Anfrage beim Server liegen und kommt in dem Moment zurück, in dem der Lauf
  /// durch ist. Damit entfällt auch die Kopplung an `scheduler.debounce-ms`, die vorher hier als
  /// Kommentar mitgepflegt werden musste.
  void scheduleReconcile() {
    _replanning = true;
    notifyListeners();

    if (_wartet) {
      // Es liegt schon eine Anfrage beim Server. Eine zweite brächte nichts — sie wartet auf
      // dasselbe Ereignis — würde aber eine weitere Verbindung offen halten. Stattdessen wird
      // direkt nach der laufenden nochmal angefragt.
      _erneutAnfordern = true;
      return;
    }
    _reconcileUhr = Stopwatch()..start();
    _aufLaufWarten();
  }

  Future<void> _aufLaufWarten() async {
    _wartet = true;
    try {
      final status = await _calendarService.awaitScheduleRun(since: _lastRunAtRaw);
      if (_entsorgt) return;

      final laufZeit = status?.lastRunAt;
      final neu = status != null &&
          laufZeit != null &&
          (_lastRunAt == null || laufZeit.isAfter(_lastRunAt!));

      if (status != null) _atRisk = status.atRisk;

      if (!neu) {
        // 204, Fehler, oder ein Signal ohne Lauf (Autoplanung ist aus). In keinem dieser Fälle
        // hat sich am Kalender etwas geändert — der teure Monatsabruf entfällt.
        _melde(status == null ? 'leer' : 'kein-lauf', false);
        _replanning = false;
        notifyListeners();
        return;
      }

      _lastRunAt = laufZeit;
      _lastRunAtRaw = status.lastRunAtRaw;

      // null heißt UNBEKANNT und nicht "keine": dann wird geladen. Nur eine ausdrückliche 0 vom
      // Server erlaubt es, den Monatsabruf zu überspringen.
      final geladen = status.changedBlocks == null || status.changedBlocks! > 0;
      if (geladen) await _pollEventsSilent();
      if (_entsorgt) return;

      _melde('longpoll', geladen);
      _replanning = false;
      notifyListeners();
    } finally {
      _wartet = false;
      if (_erneutAnfordern && !_entsorgt) {
        _erneutAnfordern = false;
        scheduleReconcile();
      }
    }
  }

  void _melde(String weg, bool geladen) {
    final uhr = _reconcileUhr;
    if (uhr == null) return;
    uhr.stop();
    debugPrint('RECONCILE ms=${uhr.elapsedMilliseconds} weg=$weg geladen=$geladen');
    _reconcileUhr = null;
  }

  /// Holt den Status im Vorbeigehen und schreibt den zuletzt gesehenen Lauf fort.
  ///
  /// Wichtig fuer den Long-Poll: hier wird auch [_lastRunAtRaw] gesetzt. Ohne das haette die
  /// erste Warte-Anfrage nach dem App-Start kein `since` und muesste blind auf das naechste
  /// Ereignis warten, statt einen schon erledigten Lauf sofort zu erkennen.
  Future<void> _pollScheduleStatus() async {
    final status = await _calendarService.getScheduleStatus();
    if (status == null) return;

    _atRisk = status.atRisk;
    final laufZeit = status.lastRunAt;
    if (laufZeit == null) return;

    _lastRunAt = laufZeit;
    _lastRunAtRaw = status.lastRunAtRaw;
  }

  /// Regelmaessiger Abgleich im Hintergrund — die Rueckfallebene, nicht der Hauptweg.
  ///
  /// Der Long-Poll wird nur nach einer EIGENEN Aenderung geoeffnet und deckt deshalb
  /// definitionsgemaess nicht ab: den naechtlichen Roll-Forward-Lauf des Servers, Aenderungen von
  /// einem anderen Geraet, eine App, die im Hintergrund war, und eine Warte-Anfrage, die
  /// unterwegs (Proxy, `adb reverse`, Doze) gestorben ist. Eine Abfrage alle 30 Sekunden ist die
  /// billigste Versicherung gegen diese Faelle und bleibt deshalb unveraendert bestehen.
  void _startPolling() {
    _pollingTimer?.cancel();
    _pollingTimer = Timer.periodic(const Duration(seconds: 30), (_) {
      _pollEventsSilent();
    });
  }

  Future<void> _pollEventsSilent() async {
    // Only poll if we have a focused day
    try {
      final month = _focusedDay;
      final firstDay = DateTime(month.year, month.month, 1);
      final lastDay = DateTime(month.year, month.month + 1, 0, 23, 59, 59);
      final newEvents = await _calendarService.getEventsInRange(firstDay, lastDay);
      // We could check if events changed before notifying, but for now just update
      _events = newEvents;
      // Die At-Risk-Liste gehoert zum selben Bestand. Sie wurde bisher nur im Nachlauf nach einer
      // eigenen Aenderung aktualisiert — ein Warnband, das ein Hintergrundlauf laengst aufgeloest
      // hatte, blieb deshalb bis zum naechsten Screenwechsel stehen.
      await _pollScheduleStatus();
      notifyListeners();
    } catch (e) {
      // ignore silently
    }
  }

  @override
  void dispose() {
    // Die Warte-Anfrage kann bis zu 35 Sekunden offen sein und ueberlebt damit jeden
    // Screenwechsel. Abbrechen laesst sie sich nicht sinnvoll — stattdessen merkt sich der
    // Provider, dass er weg ist, und jeder Rueckweg prueft das, bevor er notifyListeners ruft.
    _entsorgt = true;
    _pollingTimer?.cancel();
    super.dispose();
  }

  // Getters

  /// Alle sichtbaren Termine — uebersprungene sind bewusst nicht dabei.
  ///
  /// Ueberspringen gibt die Zeit frei; genau so soll der Tag dann auch aussehen. Bliebe der
  /// Block stehen, wuerde der Scheduler die freigegebene Zeit neu belegen und im Kalender laegen
  /// zwei Bloecke uebereinander — das sieht aus wie ein Fehler, obwohl beides stimmt.
  ///
  /// Der Block selbst bleibt serverseitig erhalten (er ist der Beleg fuer das verbrauchte
  /// Wochenpensum); zurueckholen laesst er sich direkt nach dem Ueberspringen ueber das
  /// Rueckgaengig im Hinweis.
  /// Immer nach Startzeit sortiert.
  ///
  /// Die Serverantwort ist es seit `findByUserIdAndStartTimeBetweenOrderByStartTimeAsc` zwar
  /// auch, aber das allein reicht nicht: die optimistischen Aenderungen hier ersetzen einen
  /// Eintrag AN ORT UND STELLE (`_events[i] = updated`) und `addEvent` haengt hinten an. Ein
  /// verschobener Termin behielte sonst seine alte Position in der Liste — und genau die zeigt
  /// der Homescreen an.
  List<CalendarEvent> get events {
    final sichtbar = _events.where((e) => !e.isSkipped).toList();
    sichtbar.sort((a, b) => a.startTime.compareTo(b.startTime));
    return List.unmodifiable(sichtbar);
  }
  bool get isLoading => _isLoading;
  String? get error => _error;
  DateTime get focusedDay => _focusedDay;
  DateTime? get selectedDay => _selectedDay;

  List<CalendarEvent> getEventsForDay(DateTime day) {
    // Ueber den Getter, damit uebersprungene Bloecke auch hier nicht auftauchen.
    return events.where((event) {
      return event.startTime.year == day.year &&
             event.startTime.month == day.month &&
             event.startTime.day == day.day;
    }).toList();
  }

  /// Was an einem Tag noch bevorsteht — die Sicht des Homescreens.
  ///
  /// Dort steht eine kurze Liste ("die naechsten vier"), und die war am Nachmittag regelmaessig
  /// mit dem Vormittag gefuellt: chronologisch sortiert und oben abgeschnitten zeigte sie genau
  /// das, was schon vorbei war. Gefiltert wird deshalb auf das Ende, nicht auf den Beginn — ein
  /// gerade laufender Block gehoert weiter dazu, bis er wirklich vorbei ist.
  ///
  /// Nur fuer HEUTE. Ein anderer Tag im Datumsstreifen liefert unveraendert den ganzen Tag: dort
  /// ist "was kommt noch" entweder alles (Zukunft) oder nichts (Vergangenheit), und ein leerer
  /// Montag waere keine Antwort, sondern ein Fehler.
  ///
  /// Der Kalender-Screen benutzt das bewusst NICHT — dort bleiben abgehakte Bloecke als Protokoll
  /// sichtbar (durchgestrichen und zurueckgenommen).
  List<CalendarEvent> getUpcomingEventsForDay(DateTime day) {
    final alle = getEventsForDay(day);
    final now = DateTime.now();
    final istHeute = day.year == now.year && day.month == now.month && day.day == now.day;
    if (!istHeute) return alle;

    return alle
        .where((e) => !e.isCompleted && e.endTime.isAfter(now))
        .toList(growable: false);
  }

  List<CalendarEvent> get selectedDayEvents {
    if (_selectedDay == null) return [];
    return getEventsForDay(_selectedDay!);
  }

  
  void setFocusedDay(DateTime day) {
    _focusedDay = day;
    notifyListeners();
  }

  
  void setSelectedDay(DateTime? day) {
    _selectedDay = day;
    notifyListeners();
  }

  
  Future<void> loadEventsForMonth(DateTime month) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final firstDay = DateTime(month.year, month.month, 1);
      final lastDay = DateTime(month.year, month.month + 1, 0, 23, 59, 59);
      
      _events = await _calendarService.getEventsInRange(firstDay, lastDay);
      _error = null;
      // Der geladene Monat IST ab jetzt der fokussierte. Ohne diese Zeile laed der 30s-Poll
      // (_pollEventsSilent rechnet aus _focusedDay) gleich wieder einen anderen Monat nach und
      // der gerade geholte Bestand waere nach spaetestens einer halben Minute wieder weg.
      _focusedDay = month;
      // Nebenbei den Ausgangswert für den Nachlauf setzen. Ohne ihn kostet die erste Umplanung
      // nach dem App-Start eine zusätzliche Runde: der Nachlauf müsste erst herausfinden, welcher
      // Lauf der "alte" war, bevor er einen neuen erkennen kann.
      await _pollScheduleStatus();
    } catch (e) {
      _error = 'Fehler beim Laden der Events: $e';
    }

    _isLoading = false;
    notifyListeners();
  }

  
  Future<void> loadEventsInRange(DateTime start, DateTime end) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      _events = await _calendarService.getEventsInRange(start, end);
      _error = null;
    } catch (e) {
      _error = 'Fehler beim Laden der Events: $e';
    }

    _isLoading = false;
    notifyListeners();
  }

  
  Future<bool> addEvent(CalendarEvent event) async {
    debugPrint('🕒 [CalendarProvider] addEvent started');
    try {
      debugPrint('🌐 [CalendarProvider] Calling service.createEvent');
      final created = await _calendarService.createEvent(event);
      
      if (created != null) {
        debugPrint('✅ [CalendarProvider] Event created successfully, reloading month');
        await loadEventsForMonth(_focusedDay);
        debugPrint('📊 [CalendarProvider] Month reloaded');
        scheduleReconcile();
        return true;
      }
      debugPrint('⚠️ [CalendarProvider] service.createEvent returned null');
      return false;
    } catch (e) {
      debugPrint('🔥 [CalendarProvider] Error in addEvent: $e');
      _error = 'Fehler beim Erstellen des Events: $e';
      notifyListeners();
      return false;
    }
  }

  
  // Optimistically applies the change locally (so drag-and-drop feels instant, no
  // full-month reload flicker), then syncs with the backend and reverts on failure.
  Future<bool> updateEvent(CalendarEvent event) async {
    final idx = _events.indexWhere((e) => e.id == event.id);
    final previous = idx != -1 ? _events[idx] : null;

    if (idx != -1) {
      _events[idx] = event;
      notifyListeners();
    }

    try {
      final updated = await _calendarService.updateEvent(event);

      if (updated != null) {
        if (idx != -1) {
          _events[idx] = updated;
          notifyListeners();
        } else {
          await loadEventsForMonth(_focusedDay);
        }
        // Das Backend plant im Hintergrund um — Ergebnis kurz danach nachladen.
        scheduleReconcile();
        return true;
      }
      if (idx != -1 && previous != null) {
        _events[idx] = previous;
        notifyListeners();
      }
      return false;
    } catch (e) {
      if (idx != -1 && previous != null) {
        _events[idx] = previous;
      }
      _error = 'Fehler beim Aktualisieren des Events: $e';
      notifyListeners();
      return false;
    }
  }

  
  Future<bool> deleteEvent(int id) async {
    try {
      final success = await _calendarService.deleteEvent(id);
      
      if (success) {
        await loadEventsForMonth(_focusedDay);
        scheduleReconcile();
        return true;
      }
      return false;
    } catch (e) {
      _error = 'Fehler beim Löschen des Events: $e';
      notifyListeners();
      return false;
    }
  }

  /// Hakt einen Aufgabenblock ab oder nimmt das zurück.
  ///
  /// Anders als [setPinned] bewusst NICHT optimistisch: der Server schreibt die Minuten gut
  /// (ans Lernziel oder an die Aufgabe), schließt die Aufgabe womöglich ab und plant die
  /// restlichen Blöcke neu. Nichts davon lässt sich hier vorhersagen — also gilt, was
  /// zurückkommt.
  Future<bool> setCompleted(int id, bool completed) async {
    try {
      final updated = await _calendarService.setCompleted(id, completed);
      if (updated == null) return false;

      final idx = _events.indexWhere((e) => e.id == id);
      if (idx != -1) {
        _events[idx] = updated;
        notifyListeners();
      }
      // Die Neuplanung läuft entprellt; das Nachladen holt die verschobenen Blöcke.
      scheduleReconcile();
      return true;
    } catch (e) {
      _error = 'Fehler beim Abhaken des Blocks: $e';
      notifyListeners();
      return false;
    }
  }

  /// Überspringt eine Ausführung oder holt sie zurück.
  ///
  /// Wie [setCompleted] und anders als [setPinned] bewusst NICHT optimistisch: das Überspringen
  /// gibt Zeit frei, stößt eine Neuplanung an und markiert bei einem Training zusätzlich die
  /// Session. Was daraus wird, lässt sich hier nicht vorhersagen — also gilt, was zurückkommt.
  Future<bool> setSkipped(int id, bool skipped) async {
    try {
      final updated = await _calendarService.setSkipped(id, skipped);
      if (updated == null) return false;

      final idx = _events.indexWhere((e) => e.id == id);
      if (idx != -1) {
        _events[idx] = updated;
        notifyListeners();
      }
      // Die freigegebene Zeit füllt der Scheduler entprellt nach.
      scheduleReconcile();
      return true;
    } catch (e) {
      _error = 'Fehler beim Überspringen des Blocks: $e';
      notifyListeners();
      return false;
    }
  }

  /// Pinnt ein Event fest oder gibt es wieder für den Scheduler frei.
  /// Optimistisch wie updateEvent, damit das Schloss-Symbol sofort umspringt.
  Future<bool> setPinned(int id, bool pinned) async {
    final idx = _events.indexWhere((e) => e.id == id);
    final previous = idx != -1 ? _events[idx] : null;

    if (idx != -1 && previous != null) {
      _events[idx] = previous.copyWith(isFixed: pinned);
      notifyListeners();
    }

    try {
      final updated = await _calendarService.setPinned(id, pinned);
      if (updated != null) {
        if (idx != -1) {
          _events[idx] = updated;
          notifyListeners();
        }
        scheduleReconcile();
        return true;
      }
      if (idx != -1 && previous != null) {
        _events[idx] = previous;
        notifyListeners();
      }
      return false;
    } catch (e) {
      if (idx != -1 && previous != null) {
        _events[idx] = previous;
      }
      _error = 'Fehler beim Anpinnen des Events: $e';
      notifyListeners();
      return false;
    }
  }

  // Backend auto-regenerates on every task/habit/workout/event change (see ScheduleChangedEvent),
  // but items created before that wiring existed (or edited directly in the DB) need one initial
  // backfill pass. Called once per app session — no user-facing button, this is the "automatic"
  // Reclaim-style scheduling entry point.
  Future<void> ensureScheduleGenerated() async {
    if (_hasAutoGenerated) return;
    _hasAutoGenerated = true;
    await generateSchedule(DateTime.now());
  }


  // Ohne endDate plant das Backend über seinen vollen Horizont — nur so landen Habits und
  // Workouts in jeder Woche und nicht nur in den nächsten zwei.
  Future<Map<String, dynamic>> generateSchedule(
    DateTime startDate, {
    DateTime? endDate,
  }) async {
    _isLoading = true;
    // Auch _replanning setzen, nicht nur _isLoading: der Fortschrittsbalken im Kalender hängt an
    // isReplanning. Ohne das passierte beim "Jetzt neu planen"-Knopf zwei Sekunden lang sichtbar
    // nichts. Es ist dieselbe Aussage — "es wird gerade geplant" —, also gehört sie an dasselbe
    // Flag und nicht in eine zweite Bedingung im Widget.
    _replanning = true;
    notifyListeners();

    final result = await _calendarService.generateSchedule(startDate, endDate: endDate);

    if (result['success']) {
      // Bewusst den ganzen Monat neu laden, nicht nur [startDate, endDate]: loadEventsInRange
      // ERSETZT _events durch das 14-Tage-Fenster und löscht damit den Monat, der Millisekunden
      // vorher geladen wurde — frühere Tage im Monat sahen danach leer aus.
      await loadEventsForMonth(_focusedDay);
    }

    _isLoading = false;
    _replanning = false;
    if (_entsorgt) return result;
    notifyListeners();

    return result;
  }

  
  void clearError() {
    _error = null;
    notifyListeners();
  }
}